name: dota2_heroes
description: "Flutter app for viewing dota 2 hero stats"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  go_router: ^14.2.3
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  path_provider: ^2.1.4
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  retrofit: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.12

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/rank_logo/
flutter_intl:
  enabled: true
